apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    hyops.domain: platform
    hyops.app: external-secrets
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.1.0
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
