version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:20"
      timezone: "Europe/London"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "maintenance"
    groups:
      github-actions:
        patterns:
          - "*"
