apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: academy
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: academy-website
  app.kubernetes.io/part-of: hybridops-learn
  hyops.domain: academy
  hyops.app: website
