apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-entitlements-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-entitlements-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-entitlements-api
    spec:
      initContainers:
        - name: bootstrap-runtime
          image: node:22-alpine
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -eu
              mkdir -p /app
              tar -xzf /runtime/app.tgz -C /app
              cd /app
              npm install --omit=dev --no-audit --no-fund
          volumeMounts:
            - name: app-data
              mountPath: /app
            - name: runtime-payload
              mountPath: /runtime
              readOnly: true
      containers:
        - name: api
          image: node:22-alpine
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/src/server.js
          workingDir: /app
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: platform-entitlements-api-env
            - secretRef:
                name: platform-entitlements-api-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-data
              mountPath: /app
      volumes:
        - name: app-data
          emptyDir: {}
        - name: runtime-payload
          secret:
            secretName: platform-entitlements-api-runtime
