apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: platform-keycloak-env
    literals:
      - KC_DB=postgres
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME=auth.hybridops.tech
      - KC_HOSTNAME_STRICT=true
  - name: platform-keycloak-realm
    files:
      - realm.json=realm.json
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
