apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: platform-keycloak-env
    literals:
      - KC_DB=postgres
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME=auth.hybridops.tech
      - KC_HOSTNAME_STRICT=true
      - KEYCLOAK_EVENTS_EXTENSION_JAR_URL=https://repo1.maven.org/maven2/io/phasetwo/keycloak/keycloak-events/0.29/keycloak-events-0.29.jar
  - name: platform-keycloak-realm-config
    files:
      - realm-config.json=realm-config.json
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - realm-sync-cronjob.yaml
