apiVersion: batch/v1
kind: CronJob
metadata:
  name: platform-keycloak-realm-sync
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: keycloak-config-cli
              image: quay.io/adorsys/keycloak-config-cli:6.4.1-24
              imagePullPolicy: IfNotPresent
              env:
                - name: KEYCLOAK_URL
                  value: http://platform-keycloak
                - name: KEYCLOAK_USER
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_ADMIN
                - name: KEYCLOAK_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_ADMIN_PASSWORD
                - name: KEYCLOAK_EVENTS_SHARED_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_EVENTS_SHARED_SECRET
                - name: KEYCLOAK_LOGIN_THEME
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_LOGIN_THEME
                - name: KEYCLOAK_MOODLE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_MOODLE_CLIENT_SECRET
                      optional: true
                - name: KEYCLOAK_GOOGLE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_GOOGLE_CLIENT_ID
                      optional: true
                - name: KEYCLOAK_GOOGLE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_GOOGLE_CLIENT_SECRET
                      optional: true
                - name: KEYCLOAK_MICROSOFT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_MICROSOFT_CLIENT_ID
                      optional: true
                - name: KEYCLOAK_MICROSOFT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_MICROSOFT_CLIENT_SECRET
                      optional: true
                - name: KEYCLOAK_GITHUB_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_GITHUB_CLIENT_ID
                      optional: true
                - name: KEYCLOAK_GITHUB_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: platform-keycloak-secrets
                      key: KEYCLOAK_GITHUB_CLIENT_SECRET
                      optional: true
                - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
                  value: "true"
                - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
                  value: 180s
                - name: IMPORT_FILES_LOCATIONS
                  value: /config/realm-config.json
                - name: IMPORT_VAR_SUBSTITUTION_ENABLED
                  value: "true"
              volumeMounts:
                - name: realm-config
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: realm-config
              configMap:
                name: platform-keycloak-realm-config
