apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: academy-website
  namespace: argocd
  labels:
    hyops.domain: academy
    hyops.app: website
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: academy
  source:
    repoURL: https://github.com/hybridops-tech/hybridops-workloads.git
    targetRevision: main
    path: apps/academy/website/manifests/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
