apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/platform/keycloak/overlays/onprem-learn-stage1
  - ../../apps/platform/entitlements-api/overlays/onprem-learn-stage1
  - ../../apps/academy/website/overlays/onprem-learn-stage1
