apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: academy-website
    patch: |-
      - op: replace
        path: /spec/source/path
        value: apps/academy/website/manifests/overlays/burst
