apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-entitlements-api
  namespace: argocd
  labels:
    hyops.domain: platform
    hyops.app: entitlements-api
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: entitlements
  source:
    repoURL: https://github.com/hybridops-tech/hybridops-workloads.git
    targetRevision: main
    path: apps/platform/entitlements-api/manifests/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
