apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cloudflared-tunnel
  namespace: argocd
  labels:
    hyops.domain: platform
    hyops.app: cloudflared-tunnel
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel
  source:
    repoURL: https://github.com/hybridops-tech/hybridops-workloads.git
    targetRevision: main
    path: apps/platform/cloudflared-tunnel/manifests/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
