apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-tunnel
resources:
  - deployment.yaml
commonLabels:
  app.kubernetes.io/name: platform-cloudflared-tunnel
  app.kubernetes.io/part-of: hybridops-edge
  hyops.domain: platform
  hyops.app: cloudflared-tunnel
