apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-keycloak-secrets
  namespace: keycloak
spec:
  refreshPolicy: Periodic
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: platform-keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: REPLACE_GSM_SECRET_KEYCLOAK_ADMIN
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: REPLACE_GSM_SECRET_KEYCLOAK_ADMIN_PASSWORD
    - secretKey: KEYCLOAK_EVENTS_SHARED_SECRET
      remoteRef:
        key: REPLACE_GSM_SECRET_KEYCLOAK_EVENTS_SHARED_SECRET
    - secretKey: KEYCLOAK_LOGIN_THEME
      remoteRef:
        key: REPLACE_GSM_SECRET_KEYCLOAK_LOGIN_THEME
    - secretKey: KEYCLOAK_MOODLE_CLIENT_SECRET
      remoteRef:
        key: REPLACE_GSM_SECRET_KEYCLOAK_MOODLE_CLIENT_SECRET
